[package]
distribution = "2201.8.6"
org = "ballerinax"
name = "discord"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["test-keywords"]
icon = "icon.png"
repository = "https://github.com/HussainLatiff/module-ballerinax-discord"

[build-options]
observabilityIncluded = true
