[package]
distribution = "2201.8.6"
org = "ballerinax"
name = "BAL_PACKAGE_NAME"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["test-keywords"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-BAL_PACKAGE_NAME"

[build-options]
observabilityIncluded = true
