[package]
distribution = "2201.8.6"
org = "ballerinax"
name= "discord"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Communication/discord", "Cost/Free"]
icon = "icon.png"
repository = "https://github.com/HussainLatiff/module-ballerinax-discord"

[build-options]
observabilityIncluded = true
